<?php

$this->layout(
    'layout::default',
    [
        'title' => 'Login'
    ]
);

?>

<div class="container login-page">
    <div class="page-header">
        <h1>Login</h1>
    </div>
    <div class="row">
        <div class="col-sm">
            <form action="<?php echo $this->url('login'); ?>" method="post">

                <?php if (isset($error)) : ?>
                <div class="alert alert-danger" role="alert">
                    <?php echo $error; ?>
                </div>
                <?php endif ?>

                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text"
                        class="form-control"
                        id="username"
                        name="username"
                        placeholder="Enter username" />
                </div>

                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password"
                        class="form-control"
                        id="password"
                        name="password"
                        placeholder="Enter Password" />
                </div>

                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</div>

